### ISSUE TITLE
STAR alignment parameter changing

### ISSUE THREAD

**Issue by Dylan-LElab** [y9c/pseudoU-BIDseq#14]
Thank you very much for the tool, which is very convenient to run. May I know if there are any methods to change the STAR alignment parameters?

**Comment by y9c** [comment]
Hi Dylan,

Thank you for reaching out. Unfortunately, in the current version, changing the STAR alignment parameters is not straightforward and requires running the code from scratch. Could you please let me know which specific STAR parameters you would like to modify? I can look into implementing a patch in the current version to accommodate these changes.

**Comment by Dylan-LElab** [comment]
Thank you very much for your response. I would like to modify the alignment parameters by changing the --alignIntronMax setting to 1.

**Comment by y9c** [comment]
Yes. It is possible to do so. I have push a new test version for your application. To use this, you can add the following chunk into your data.yaml file. 

```yaml
star_params:
  alignEndsType: Local
  scoreDelOpen: -1
  scoreDelBase: -1
  scoreInsOpen: -2
  scoreInsBase: -2
  outFilterMatchNmin: 15
  outFilterMatchNminOverLread: 0.8
  outFilterMismatchNmax: 10
  outFilterMismatchNoverLmax: 0.2
  outFilterIntronMotifs: RemoveNoncanonicalUnannotated
  alignSJDBoverhangMin: 1
  alignIntronMax: 1
  alignSJoverhangMin: 5
  chimSegmentMin: 20
  chimOutType: WithinBAM HardClip
  chimJunctionOverhangMin: 15
  chimScoreJunctionNonGTAG: 0
  outFilterMultimapNmax: 10
  outFilterMultimapScoreRange: 0
  outSAMmultNmax: -1
  outMultimapperOrder: Random
  outSAMattributes: NH HI AS nM NM MD jM jI MC ch
```

and run the code by:

```bash
apptainer run docker://y9ch/bidseq:test
```
