### ISSUE TITLE
Error in rule gap_realign

### ISSUE THREAD

**Issue by Jarvis559** [y9c/pseudoU-BIDseq#8]
Hi y9c!
I am trying your pseudoU-BIDseq pipeline using the SRRSRR15082607,SRR15082609 and SRR15082610.
And I have the following error when run the pipeline,
```
[Wed Jan 10 14:11:17 2024]
Error in rule gap_realign:
    jobid: 25
    output: .tmp/mapping_realigned_unsorted/HeLaWT-rep1-treated_run1_contamination.cram
    shell:
        
        /pipeline/bin/realignGap -r /disk/user_18/jky_project/genome/Mesomycoplasma_hyorhinis_ATCC_17981/Mesomycoplasma_hyorhinis_ATCC_17981.fna -i .tmp/mapping_unsort/HeLaWT-rep1-treated_run1_contamination.bam -o .tmp/mapping_realigned_unsorted/HeLaWT-rep1-treated_run1_contamination.cram
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job gap_realign since they might be corrupted:
.tmp/mapping_realigned_unsorted/HeLaWT-rep1-treated_run1_contamination.cram
```

I wonder what can I do, thank you so much!

**Comment by y9c** [comment]
Hi @Jarvis559,

Could you attach the full log file for debugging?

**Comment by Jarvis559** [comment]
[2024-01-10T125527.473221.snakemake.log](https://github.com/y9c/pseudoU-BIDseq/files/13884416/2024-01-10T125527.473221.snakemake.log)

**Comment by y9c** [comment]
Seem that the log file is incomplete, which does not show the command that was used. What is the reference sequence you used in the data.yaml file.

**Comment by Jarvis559** [comment]
**Thanks for your reply! This is my first test data.yaml file:**
```
reference:
  contamination:
    fa: /disk/user_18/jky_project/genome/Mesomycoplasma_hyorhinis_ATCC_17981/Mesomycoplasma_hyorhinis_ATCC_17981.fna
  genes:
    fa: /disk/user_18/jky_project/genome/GRCh38.p14/GRCh38.p14.sncRNA.fa
  genome:
    fa: /disk/user_18/jky_project/genome/GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.fna
    star: /disk/user_18/jky_project/index/star/GRCh38.p14/GRCh38.p14

samples:
  HeLaWT-rep1-input:
    data:
      - R1: /disk/user_18/jky_project/BID_project/learning/rawdata/HeLa_input_1.fastq.gz
    group: HeLaWT
    treated: false
  HeLaWT-rep1-treated:
    data:
      - R1: /disk/user_18/jky_project/BID_project/learning/rawdata/HeLa_BID_1.fastq.gz
    group: HeLaWT
    treated: true
  HeLaWT-rep2-treated:
    data:
      - R1: /disk/user_18/jky_project/BID_project/learning/rawdata/HeLa_BID_2.fastq.gz
    group: HeLaWT
    treated: true

```

**And now i am trying the second test without the input of contamination reference genome sequence:**

```

# Max number of cores for all the running jobs at the same time
cores: 50

barcode: "NNNNNXXX-XXXNNNNNATCACG"


# NOTE: relative path of reference and sample data should relative to current config file, rather than workdir
reference:
  genes:
    fa: /disk/user_18/jky_project/genome/GRCh38.p14/GRCh38.p14.sncRNA.fa
  genome:
    fa: /disk/user_18/jky_project/genome/GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.fna
    star: /disk/user_18/jky_project/index/star/GRCh38.p14/GRCh38.p14

samples:
  HeLaWT-rep1-input:
    data:
      - R1: /disk/user_18/jky_project/BID_project/learning/rawdata/HeLa_input_1.fastq.gz
    group: HeLaWT
    treated: false
  HeLaWT-rep1-treated:
    data:
      - R1: /disk/user_18/jky_project/BID_project/learning/rawdata/HeLa_BID_1.fastq.gz
    group: HeLaWT
    treated: true
  HeLaWT-rep2-treated:
    data:
      - R1: /disk/user_18/jky_project/BID_project/learning/rawdata/HeLa_BID_2.fastq.gz
    group: HeLaWT
    treated: true
```
